FROM golang:1.21.3 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o card-checker cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/card-checker /app/card-checker
WORKDIR /app
EXPOSE 8081
CMD ["./card-checker"]
